[package]
name = "vine-lsp"
version = "0.0.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
glob = "0.3.1"
tokio = { version = "1.41.1", features = ["full"] }
tower-lsp = "0.20.0"
vine = { path = "../vine" }

[lints.clippy]
absolute_paths = "warn"
