name: Docs

on:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - run: nix build .#docs -L

      - run: nix run nixpkgs#wrangler -- pages deploy result --project-name vine-dev --branch ${{ github.ref_name }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - uses: actions/configure-pages@v3
        if: github.ref_name == 'main'

      - uses: actions/upload-pages-artifact@v3
        if: github.ref_name == 'main'
        with:
          path: "result"

      - id: deployment
        if: github.ref_name == 'main'
        uses: actions/deploy-pages@v4
