name: Integration

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  integration-test:
    runs-on: self-hosted
    timeout-minutes: 15
    permissions: read-all
    strategy:
      fail-fast: false
      matrix:
        command:
          - build github:nilscrm/liana#checks.x86_64-linux.example
          - flake check github:nilscrm/sat-vi
          - flake check github:nilscrm/vine-page-rank
    steps:
      - uses: actions/checkout@v3
      - run: nix ${{ matrix.command }} --override-input vine . -L

  integration-tests:
    needs: [integration-test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Aggregate integration test results
        run: |
          [[ "${{ needs.integration-test.result }}" == "success" ]]

  mainline:
    needs: [integration-tests]
    if: ${{ github.ref_name == 'dev' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git fetch origin main
          if ! git merge-base --is-ancestor @ origin/main; then
            git push origin `git rev-parse @`:main
          fi

  notify:
    needs: [mainline]
    if: ${{ always() && github.ref_name == 'dev' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v3
      - name: open issue
        if: ${{ needs.mainline.result == 'skipped' || needs.mainline.result == 'failure' }}
        run: |
          gh issue reopen 484
          gh issue edit 484 --add-assignee ${{ github.event.sender.login }}
        env:
          GH_TOKEN: ${{ github.token }}
      - name: close issue
        if: ${{ needs.mainline.result == 'success' }}
        run: |
          git fetch origin main
          if [[ `git rev-parse dev` == `git rev-parse origin/main` ]]; then
            gh issue close 484
            gh issue edit 484 --remove-assignee @me,`gh issue view 484 --json assignees --jq '[.assignees.[].login] | join(",")'`
          fi
        env:
          GH_TOKEN: ${{ github.token }}
